const MUSIC_AUDIO = 'MUSIC_AUDIO';
const MUSIC_MUTE = 'MUSIC_MUTE';
const SOUND_MUTE = 'SOUND_MUTE';
const MUSIC_UNMUTE = 'MUSIC_UNMUTE';
const SOUND_UNMUTE = 'SOUND_UNMUTE';
const LEVEL_CHANGE = 'LEVEL_CHANGE';
const SIZE_CHANGE = 'SIZE_CHANGE';
const TIMER_CHANGE = 'TIMER_CHANGE';
const GAME_START = 'GAME_START';
const GAME_STATUS_CHANGE = 'GAME_STATUS_CHANGE';
const GAME_TOKEN_CLICK = 'GAME_TOKEN_CLICK';
const GAME_TOKEN_CLICK_START = 'GAME_TOKEN_CLICK_START';
const GAME_BOMB_INC = 'GAME_BOMB_INC';
const GAME_BOMB_DEC = 'GAME_BOMB_DEC';
const GAME_BOMB_START_COUNT = 'GAME_BOMB_START_COUNT';
const GAME_TIMER_START = 'GAME_TIMER_START';
const GAME_TIMER_SEC_DEC = 'GAME_TIMER_SEC_DEC';
const GAME_TIMER_MIN_DEC = 'GAME_TIMER_MIN_DEC';
const GAME_STOPWATCH_START = 'GAME_STOPWATCH_START';
const GAME_STOPWATCH_SEC_INC = 'GAME_STOPWATCH_SEC_INC';
const GAME_STOPWATCH_MIN_INC = 'GAME_STOPWATCH_MIN_INC';

export {
  MUSIC_AUDIO,
  MUSIC_MUTE,
  SOUND_MUTE,
  MUSIC_UNMUTE,
  SOUND_UNMUTE,
  LEVEL_CHANGE,
  SIZE_CHANGE,
  TIMER_CHANGE,
  GAME_START,
  GAME_STATUS_CHANGE,
  GAME_TOKEN_CLICK,
  GAME_TOKEN_CLICK_START,
  GAME_BOMB_INC,
  GAME_BOMB_DEC,
  GAME_BOMB_START_COUNT,
  GAME_STOPWATCH_START,
  GAME_STOPWATCH_SEC_INC,
  GAME_STOPWATCH_MIN_INC,
  GAME_TIMER_SEC_DEC,
  GAME_TIMER_MIN_DEC,
  GAME_TIMER_START,
};
