const MUSIC_MUTE = 'MUSIC_MUTE';
const SOUND_MUTE = 'SOUND_MUTE';
const MUSIC_UNMUTE = 'MUSIC_UNMUTE';
const SOUND_UNMUTE = 'SOUND_UNMUTE';
const LEVEL_CHANGE = 'LEVEL_CHANGE';
const SIZE_CHANGE = 'SIZE_CHANGE';
const TIMER_CHANGE = 'TIMER_CHANGE';
const GAME_START = 'GAME_START';
const GAME_STATUS_CHANGE = 'GAME_STATUS_CHANGE';

export {
  MUSIC_MUTE,
  SOUND_MUTE,
  MUSIC_UNMUTE,
  SOUND_UNMUTE,
  LEVEL_CHANGE,
  SIZE_CHANGE,
  TIMER_CHANGE,
  GAME_START,
  GAME_STATUS_CHANGE,
};
